### ISSUE TITLE
Add to documentation example how write test as typescript

### ISSUE THREAD

**Issue by rebas82** [codeceptjs/CodeceptJS#1276]
for new users, who need write tests in typescript, it will be useful guide, how write test in codeceptjs.

For example, on this link https://github.com/angular/protractor/tree/5.4.1/exampleTypescript have protractor guide fore typescript.

**Comment by rebas82** [comment]
Many companies where is used angular is used typescript. This guide will help use codeceptjs for tests, better then protractor.

Right now is in codeceptjs documentation only info about TypeScript Definitions. That is not enough.

**Comment by rebajz** [comment]
We must, because we have project, where is used windows desktop app with CEF browser, where running Angular app ;-). Some code is in C, C# and some in typescript.

Tests are in the same git with project, typescript is everywhere...

Values go to / go from hardware device, different type can destroy hardware. :-(

In some test we must have control on windows desktop app (we use AutoIt) and when we open device (CEF browser) right now we testing with protractor (e2e, screenshots, rest). I will like this change (codeceptjs), because protractor is very hard for reading non technical people.

**Comment by LukoyanovE** [comment]
@DavertMik , yep, my project uses TS as main language, so specs must be written in TS too.
I'm use TS with `codeceptjs run`. 
And there are some difficulties with TS in codecept.
Like definitions, TS-node runner with `codecept run-multiple`.

I tried to use compiling by `tsc` before test run, but it looks a little ugly solution.
But it worked.

Now, I'am use `ts-node`.

I spent a bunch of time to correctly set framework for TS.
I thought about article writing for Medium/Habr as a guide for others.
Maybe it will a draft for repository guide

**Comment by rebajz** [comment]
yes, right now is difficult to use codeceptjs tests, page and steps objects saved as ts files.

**Comment by karunandrii** [comment]
Yes `ts-node` is what you need. Use it with `-F` to start faster. Or register it in bootstrap like this 
```
require('ts-node').register({
    fast: true,
    project: 'your-tsconfig.json'
});
```
But in this case, you'd need to have `ts-node` as your dependency
Also, **your ts files should be separated form your js files.** Everything else - just the same, create class, export it and enjoy.

**Comment by LukoyanovE** [comment]
@karunandrii , not all
I use ts-node, and cannot use `bootstrap` method. Cause it's called after helpers, steps importing.
It does not allow to use TS fully.

Now I'm use `ts-node codeceptjs run` - it works for most of features.
But `run-multiple` does not work with it due to it's implementation.

I made possible solution. But it is under review, and maybe it will be changed.
It will allow use TS with all comands (if I did not miss something)
#1294

**Comment by zanimonets** [comment]
I agree that there is no need to add information to run TS tests. That five lines in docs should be more than enough! Sorry for the crystal ball is not attached. You can do whatever you want. But in general the best way in this case is to consider another framework to use
