### ISSUE TITLE
Smart Wait with puppeteer

### ISSUE THREAD

**Issue by Nazanin1369** [codeceptjs/CodeceptJS#1277]
#### What are you trying to achieve?
Define Smart waits using puppeteer

#### What do you get instead?
I need to set wait on each statement
> Provide console output if related. Use `--verbose` mode for more details.

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version:
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by PeterNgTr** [comment]
smartWait is not there for puppeteer, I believe

**Comment by DavertMik** [comment]
Yeah, in Puppeteer it was not out of the box so we will need to implement it in a different way. Anyway, I think it's possible to implement it.

**Comment by Nazanin1369** [comment]
I can take this enhancement. Since we need it for our tests

**Comment by DavertMik** [comment]
Cool. Thank you.

Let me write here the ideas behind SmartWait:

SmartWait was created because there was implicit wait API in WebDriver.
https://www.seleniumhq.org/docs/04_webdriver_advanced.jsp So basically it works by turning on/off implicit waits when a CSS/XPath selector is searched.

However, for Puppeteer there is no such API so this functionalioty should be implemented manually.

SmartWait works only for CSS/XPath locators, because when we do fuzzy search we try different locators. So a link or button is not found we should search by image inside a link, span inside link, etc. So you can make few empty tries before getting a valid result. So SmartWait should not work for fuzzy locators.

You can use either promise-retry library or setInterval to make a poll for a new elements.

A basic example.
```js
// inside findClickable: 

if (!matchedLocator.isFuzzy()) {
    // make a poll and when element is found return it
    // return findElements.call(this, contextEl, matchedLocator.simplify());
  }

```

**Comment by maxx-dev** [comment]
You could specify a custom step (in your steps_file.js) to get this working:
```
clickWait: function (el) {
      this.waitForElement(el, 5); // secs
      this.click(el);
}
```

Then use it as 
```
I.clickWait('.someClass')
```

**Comment by DavertMik** [comment]
I don't think it is needed with retryFailedStep plugin
