### ISSUE TITLE
waitForRequest doesn't capture request quick enough

### ISSUE THREAD

**Issue by SeroK** [codeceptjs/CodeceptJS#1464]
I use puppeteer for running click tests on a web application. A couple of test cases require me to find out whether or not  a network request is sent to fetch a file from server. To do this I use puppeteer's [waitForRequest](https://codecept.io/helpers/Puppeteer#waitforrequest) method. 

However the requests aren't captured consistently. On multiple occasions the command times out which results in a failed test. The chrome dev tools on the other hand capture the request while the test is running.

In verbose mode I get this feedback in console
```bash
I wait for request "http://localhost:4200/assets/img/cursor/zoom-in.cur"
[1] Error | TimeoutError: Timeout exceeded while waiting for event
Emitted | step.failed (I wait for request "http://localhost:4200/assets/img/cursor/zoom-in.cur")
Emitted | step.finish (I wait for request "http://localhost:4200/assets/img/cursor/zoom-in.cur")
[1] Error | TimeoutError: Timeout exceeded while waiting for event
```
This is the test scenario 
```js
I.click('.zoom');
I.waitForRequest("http://localhost:4200/assets/img/cursor/zoom-in.cur")
I.seeElement(".zoom-menu");
```

### Details

* CodeceptJS version: 2.02
* NodeJS Version: 9.11.2
* Operating System: Windows 10 (1809)
* Configuration file:

```js
exports.config = {
  tests: './codecept-tests/*.js',
  timeout: 10000,
  output: './output',
  helpers:
  {
    Puppeteer:
    {
      url: 'http://localhost',
      show: true,
      windowSize: '1280x720',
      chrome:
      {
        defaultViewport: { width: 1280, height: 720 }
      }
    }
  },
  include: {},
  bootstrap: false,
  mocha: {},
  name: 'frontend',
  plugins: { screenshotOnFail: { enabled: true } }
}
```

**Comment by inigo-martin** [comment]
In my case, the problem was that the Application was firing the Request before the _waitForRequest_ took place. So it never catched the Request.

That is because Puppeteer waits 100ms (by Default) after actions like click, doubleClick or PressKey.

[Puppeteer Config waitForAction](https://codecept.io/helpers/Puppeteer#configuration)

To solve the issue, I just had to set this _waitForAction_ parameter to 0:

`exports.config = {
    tests: './integration/*_test.js',
    output: './integration/output',
    helpers: {
        Puppeteer: {
            url: 'http://localhost:3040',
            restart: false,
            show: true,
            windowSize: '1280x960',
            waitForAction: 0,
            chrome: {
                defaultViewport: {
                    width: 1280,
                    height: 800,
                },
            },
        },
        MockRequest: {},
    },
    include: {},
    bootstrap: null,
    mocha: {
        reporterOptions: {
            reportDir: './integration/output',
        },
    },
};`

**Comment by Meekohi** [comment]
fwiw I do like:

```
await Promise.all([
  I.click('.zoom'),
  I.waitForRequest("http://localhost:4200/assets/img/cursor/zoom-in.cur"),
])
```

**Comment by aelzhanova** [comment]
I have the same issue

**Comment by aelzhanova** [comment]
if it still actual for you I solved this problem: https://medium.com/@alsu.gareeva/codeceptjs-puppeteer-how-to-catch-too-fast-requests-1809e8c49fcf

**Comment by CyberLight** [comment]
It looks like your config for codeceptjs has a key `waitForNavigation: 'networkidle0`
```javascript
exports.config = {
  tests: 'tests/*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      url: process.env.CODECEPTJS_URL,
      show: false,
      waitForNavigation: 'networkidle0', // <-------- this adds waiting for network activity to end before executing, for example "click" action
      windowSize: '1200x900',
      chrome: {
        args: ['--no-sandbox'],
      },
    },
  },
```
and this blocks of execution for the following sumaltenous steps:
```
  await Promise.all([
    I.waitForRequest(some_url_here),
    I.click(refreshButton),
  ]);
```
because if we look at source code of click step for codeceptjs https://github.com/codeceptjs/CodeceptJS/blob/7df680264b6b0d079651d7cabb818926e53d494b/lib/helper/Puppeteer.js#L2208
![image](https://user-images.githubusercontent.com/2742061/89859379-b250ce80-dbc2-11ea-9eba-f9808e8089d5.png)
then we will see that options.waitForNavigation will be put on the promise list.
If the step before clicking causes any network activity, then the click will wait for the network to end if you specified options.waitForNavigation

**SOLUTION:**
*  Don't use **waitForNavigation** option for **Puppeteer** helper. Only use **waitForNavigation** inside your scenario and your live will be better! :). Because global setting for waiting navigation will break some of your scenarios without any information about this fact.

**Comment by SeroK** [comment]
Thanks a bunch! The solutions proposed by **Meekohi** and **aelzhanova** worked for my use case!

Sorry for the late reply

**Comment by Meekohi** [comment]
Hey @il-bot you are misunderstanding how puppeteer works and what `.wait` does. There is only _one_ instance of Chrome running behind the scenes -- when you call `I.wait(1)` you are asking that instance to wait for one second before doing anything else. So when you run your example above, even though all the functions are technically called immediately, they are being sent to a single Chrome instance which will do them in order. Generally this is what you want and expect.

The point of something like my example:
```
await Promise.all([
  I.click('.zoom'),
  I.waitForRequest("http://localhost:4200/assets/img/cursor/zoom-in.cur"),
])
```
is that you want to avoid the 100ms delay after clicking, because a fast response might come back _before_ `waitForRequest` gets called in that scenario, which leads to flakey results. Actually the other order might make the intention clearer although it makes no difference -- you basically want to start waiting for the request, then click the button.
