### ISSUE TITLE
Unable to use require inside include codecept.conf

### ISSUE THREAD

**Issue by vitaly87** [codeceptjs/CodeceptJS#1685]
#### What are you trying to achieve?
I am trying to use 

codecept.conf:

```
 include: {
    I: "./logicalOperations.js",
    consts: require("./common/consts").consts,
  },



```
my page looks like this:

```
const {
    I,
    consts
} = inject();


```
#### What do you get instead?
 

>    The "path" argument must be of type string. Received type object

> Provide console output if related. Use `--verbose` mode for more details.

```bash

// paste test
```

### Details

* CodeceptJS version: codeceptjs version 2.1.3
* NodeJS Version:
* Operating System:
* Protractor || WebDriverIO || Nightmare version (if related)
* Configuration file:

```js
# paste suite config here
```

**Comment by hubidu** [comment]
You can only use page objects in include, but you do not require them, you just specify the path to the page object file (as a string). Hence the error you get, since "require("./common/consts").consts" returns an object not a path (i. e. a string).

If you want to require files you can do so directly in your tests as you would in any other nodejs file. You don't have to use page objects and dependency injection .
E. g.

```
const {consts} = require("./common/consts")

Feature('foo')

Scenario('bar', (I) => {
   // use consts
  consts.something ...
})
```
