### ISSUE TITLE
How to pass globals from main thread to run-multiple run

### ISSUE THREAD

**Issue by vitaly87** [codeceptjs/CodeceptJS#1858]
Hi,
I am using globals with nodejs +webdriver and I cant see any working way to pass globals with un-multiple
same for run-workers.

I will be happy to see some examples

**Comment by Naimadnap** [comment]
What kind of globals?

**Comment by vitaly87** [comment]
I am trying to set some data on global , this data is dynamic the set is from bootstrup, the issue when you run with workers the global change workers.any update about this issue?

**Comment by koushikmohan1996** [comment]
@vitaly87 After these changes https://github.com/Codeception/CodeceptJS/pull/2115 you can share data from main thread to worker or vice versa using `share(data)` API

**Comment by SamBreaksThings** [comment]
@koushikmohan1996 Just bumped into your PR, thanks for the reference. I've got a question, would the import from `inject` supposed to work only within a test? Or would I be able to do it at root level of the file? In this [example](https://github.com/codeceptjs/CodeceptJS/pull/2115/files#diff-37f85613ec33373acfd2930f4f7665e9R7), you are importing the shared data from `inject` inside the test and it works fine. The same doesn't work when trying to import from root level, maybe because the root level imports are evaluated way earlier?
