### ISSUE TITLE
Screenshots On Failure Are Not Saved When Using REST Helper

### ISSUE THREAD

**Issue by KateKorneeva** [codeceptjs/CodeceptJS#2508]
#### What are you trying to achieve?
Have a screenshot saved on failure https://codecept.io/basics/#screenshot-on-failure

#### What do you get instead?
Screenshot is not saved in `/output`
The bug was introduced in `2.6.7`. In `2.6.6` it works fine

### Details

* CodeceptJS version: 2.6.7
* NodeJS Version: v12.16.1

**Comment by pablopaul** [comment]
@KateKorneeva must be something specific with the project configuration, here is an example with CodeceptJS v 2.6.7 which saves screenshot on failure:

Pipeline run: https://gitlab.com/paulvincent/codeceptjs-bug-report-template/-/jobs/663207933
Failure screenshot: https://gitlab.com/paulvincent/codeceptjs-bug-report-template/-/jobs/663207933/artifacts/file/ci_artifacts/Bug_1.failed.png

**Comment by pablopaul** [comment]
The screenshot can´t be saved if the REST helper is configured after a helper which supports the `saveScreenshot()` method, so that it becomes unavailable.

See this failing pipeline: https://gitlab.com/paulvincent/codeceptjs-bug-report-template/-/jobs/663639282

```
 › <screenshotOnFail> Test failed, saving screenshot
 › <TypeError: helper.saveScreenshot is not a function> undefined
```

The [whole logic to determine "the current helper" in screenshotOnFail](https://github.com/codeceptjs/CodeceptJS/blob/master/lib/plugin/screenshotOnFail.js#L51) looks pretty error prone to me, and with [the latest addition](https://github.com/codeceptjs/CodeceptJS/compare/2.6.6...2.6.7#diff-058e73421cf0c9a35663d3c36775ea7cR11) of `REST` into `standardActingHelpers.js` it is not compatible anymore.

@PeterNgTr do you have an idea for a good fix? Can you help with advise @DavertMik pleae ?

**Comment by PeterNgTr** [comment]
Oh no, so probably my last PR to add REST helper into that standard acting helpers. I would guess instead of adding it to the standard list, adding that REST helper into the delay plugin only. How does it sound? @pablopaul

**Comment by pablopaul** [comment]
@PeterNgTr sounds good to me, thanks. Are you going to open a PR?

**Comment by PeterNgTr** [comment]
> @PeterNgTr sounds good to me, thanks. Are you going to open a PR?

hey @pablopaul here is the fix https://github.com/codeceptjs/CodeceptJS/pull/2513
