### ISSUE TITLE
event.test.started is not triggered for the first scenario

### ISSUE THREAD

**Issue by MickaelTH** [codeceptjs/CodeceptJS#2602]
#### What are you trying to achieve?

Try to get the name of the scenario when it starts.

#### What do you get instead?

The first scenario seems to not trigger the event or no object is passed to it, but the next scenarios are perfectly working.

> Provide console output if related. Use `--verbose` mode for more details.

![image](https://user-images.githubusercontent.com/26375917/94427473-57e2f000-01b9-11eb-8eea-c8027ec831d0.png)

> Provide test source code if related

```js
Feature('Debug')

Scenario('Scenario 0', async (I) => {
	I.wait(5);
});

Scenario('Scenario 1', async (I) => {
	I.wait(5);
});
```
In custom_steps.js

```js
const event = require('codeceptjs').event;

module.exports = function() {
event.dispatcher.on(event.test.started, function (test) {
    console.log(`Test title is: ${test.title}`)
  });
}
```
### Details

* CodeceptJS version: 2.6.11
* NodeJS Version: 10.19.0
* Operating System: Ubuntu 20.04
* puppeteer version (if related): N/A
* Configuration file:

```js
exports.config = {
  include: {
    I: "./custom_steps.js"
  },
}
```

**Comment by brunoklein** [comment]
Hey Mickael, I guess you should import your custom_steps.js file inside of `helpers`:

```
exports.config = {
  tests: './*_test.js',
  output: '',
  helpers: {
    Puppeteer: {
      url: 'http://google.com',
      show: true,
      windowSize: '1200x900'
    },
    CustomHelper: {
      require: './custom_helper.js'
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codeceptjs-lab',
  plugins: {
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Tests**

<img width="381" alt="image" src="https://user-images.githubusercontent.com/6807173/94431257-556e9f00-0195-11eb-8ed7-8b9f38abaaa1.png">

**Output**

<img width="308" alt="image" src="https://user-images.githubusercontent.com/6807173/94431187-3e2fb180-0195-11eb-9bec-f66b8ef7f5c5.png">

**Comment by MickaelTH** [comment]
@brunoklein Well thanks, that's interesting.

Did you just use the same file and moved it as custom helper or you convert it to use the hooks? Because I do not see the started hook from the documentation:

https://codecept.io/helpers/#hooks

Or is the event listeners being considered like a custom helper?

**Comment by brunoklein** [comment]
@MickaelTH you are welcome!

Yes, first option - I used the same code from the custom_step.js file that you shared 👍 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/6807173/94524167-8650e180-0232-11eb-8160-3652d894e703.png">

**Comment by brunoklein** [comment]
@MickaelTH you are welcome!

Yes, first option - I used the same code from the custom_steps.js file that you shared 👍 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/6807173/94525347-3d9a2800-0234-11eb-84b8-3efbc5b5b15a.png">


> I always thought that the custom helper should be a class that extends codecept_helper

I guess you are right! I've updated my first comment to be consistent. Thanks!

**Comment by brunoklein** [comment]
@MickaelTH you are welcome!

Yes, first option - I used the same code from the custom_steps.js file that you shared 👍 
I updated my first comment to be consistent.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/6807173/94525347-3d9a2800-0234-11eb-84b8-3efbc5b5b15a.png">


> I always thought that the custom helper should be a class that extends codecept_helper

I think we don't necessarily need to extends codecept_helper in order to import files inside `helper` - but I'm not the best person to answer it :(

Thanks!

**Comment by brunoklein** [comment]
@MickaelTH you are welcome!

Yes, first option - I used the same code from the custom_steps.js file that you shared 👍
I updated my first comment to be consistent as well.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/6807173/94526459-d67d7300-0235-11eb-9b4f-8ba5a1a9c206.png">

> I always thought that the custom helper should be a class that extends codecept_helper

I think we don't necessarily need to extend codecept_helper in order to import files inside helper - but I'm not the best person to answer it :(
