### ISSUE TITLE
Failures are not listed at the end when using run-workers

### ISSUE THREAD

**Issue by ElVisPL** [codeceptjs/CodeceptJS#2621]
#### What are you trying to achieve?
I would like to see steps of failed tests when using run-workers

I understand problem described in [docs](https://codecept.io/parallel/#parallel-execution-by-workers):
> This command is similar to run, however, steps output can't be shown in workers mode, as it is impossible to synchronize steps output from different processes.

However maybe it would be possible to flush steps of failed tests when all workers finish?

#### What do you get instead?
I see empty section:
```
[1] -- FAILURES:

error Command failed with exit code 1.
```
### Details

* CodeceptJS version: 3.0.0
* NodeJS Version: 12.18.0
* Operating System: MacOS Catalina 10.15.5
* puppeteer 5.3.1

**Comment by asolodova** [comment]
Same for Webdriver

**Comment by drfiresign** [comment]
Hi folks, I think I might have solved this, but when running tests with `npm test` I get two failures that I'm not sure about. The fix applies the `_updateFinishedTests()` method to test object after `event.test.after` event. Bug seems to be occurring because this event was the only one receiving the `test.err` object, but it wasn't attaching the test id. When the `workers.printResults()` method was later called in `lib/command/run-workers.js`, no test id was present to iterate over in lines 415-417 of `lib/workers.js` when building the failed test results. I might have gone about this fix the wrong way, maybe there's a better way to deal with when the error is attached, but this is as far as I got towards understanding the worker system.

Here's the branch and the change on my fork that fixes the issue (for me at least):  https://github.com/codeceptjs/CodeceptJS/compare/3.x...drfiresign:fix/2621

The test failures I'm getting:

```
  1) Workers
       should run simple worker:

      Uncaught AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Workers.<anonymous> (test/unit/worker_test.js:31:22)
      at Workers._finishRun (lib/workers.js:379:10)
      at Worker.<anonymous> (lib/workers.js:367:14)
      at Worker.[kOnExit] (internal/worker.js:240:10)
      at Worker.<computed>.onexit (internal/worker.js:174:20)

  2) Workers
       should run worker with custom config:

      Uncaught AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
      
      at Workers.<anonymous> (test/unit/worker_test.js:110:22)
      at Workers._finishRun (lib/workers.js:379:10)
      at Worker.<anonymous> (lib/workers.js:367:14)
      at Worker.[kOnExit] (internal/worker.js:240:10)
      at Worker.<computed>.onexit (internal/worker.js:174:20)
```

The two failures are on `expect(status).equal(false)`, and I don't know enough about what these tests are trying to do to know if just changing this to `.equal(true)` instead would be an appropriate fix. Maybe there's another reason they're set this way and I'm missing something. 

If anyone can take a look and double check that this fix will be appropriate in spite of the test failure (or can walk me through how to appropriately modify the tests), it would be appreciated.

**Comment by chwolf** [comment]
@drfiresign I checked your change locally and yeah, at least the errors are now printed. :)
It would be great if also the previous Test Steps are printed - the same way as it happens when using only `codecepths run ...` command, but your solution is better than nothing. 👍 
Currently i have no idea how to improve your change or if calling `this._updateFinishedTests` has any side-effects, but we really need the specific failure printed in the summary so i would give it a - ready to merge - and then we can improve it afterwards.

**Comment by haveac1gar** [comment]
This seems to will be solved here: https://github.com/codeceptjs/CodeceptJS/pull/2857, take a look
