### ISSUE TITLE
Unknown engine "react" error using react selectors

### ISSUE THREAD

**Issue by dj-neza** [codeceptjs/CodeceptJS#2696]
#### What are you trying to achieve?
Hi! I'm trying to test a React application with Codecept and Playwright using the React locators mentioned [here](https://codecept.io/react/#locators). An example of using them in my tests:  
`I.click({ react: 'MyComponent', props: { name: 'Test name' } });`

#### What do you get instead?
An error occurs in the test in the above line with the message `Unknown engine "react" while parsing selector react=MyComponent`.

> Provide test source code if related

```js
Scenario('Test scenario', ({ I }) => {
  I.click({ react: 'MyComponent', props: { name: 'Test name' } });
});
```

### Details

* CodeceptJS version: 3.0.2
* NodeJS Version: 14.7.0
* Operating System: MacOS
* Playwright: 1.6.2
* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: 'tests/*.test.js',
  output: 'tests/output',
  helpers: {
    Playwright: {
      url: 'Test url',
      show: true,
      browser: 'chromium',
      waitForNavigation: "networkidle",
    },
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'test-app',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}
```

**Comment by zs-zs** [comment]
Unfortunately this is not implemented yet.

[The docs](https://codecept.io/react/#locators) says: _"**In WebDriver and Puppeteer** you can use React locators in any method where locator is required"_

So it will work with WebDriver and Puppeteer, but not with Playwright. I had the same problem few days ago.

I also found this [comment](https://github.com/codeceptjs/CodeceptJS/pull/2173#issuecomment-582707326) in the PR which introduced Playwright to this library. The author mentions:

_React locators not supported (volunteers to fix this!)_

So I guess there were no volunteers since February... I switched to Puppeteer until it gets supported.

**Comment by dj-neza** [comment]
Thanks for clarifying, I now see that it says so [here](https://codecept.io/react/#locators) as well, was too busy looking at the syntax 😅 How inconvenient was switching to Puppeteer then? Considering that we only have the setup and some most basic cases implemented for now, it might still be reasonable to switch 🤔

**Comment by zs-zs** [comment]
Switching from CodeceptJS+Playwright to CodeceptJS+Puppeteer?
I'm not an expert of this library, but I guess it depends on how much Playwright-specific stuff are you using in your CodeceptJS helpers... If you don't have any custom helpers theoretically it should be very simple, only a config change...

But I have to say I'm a bit disappointed in the CodeceptJS React support even with Puppeteer. The docs mention that "you can use React locators in any method where locator is required" but actually it's not the case. I was digging a bit in the CodeceptJS sourcecode, and you can clearly see in [this file](https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/helper/Puppeteer.js) that the "findReact" function is not called from every helper function, only a subset of them. I don't have time to create PR for this right now.

Worst case, you can do the same what CodeceptJS is doing in order to support React: they are using this selector library called "resq" - they evaluate the library's script in the browser's context, then they wind it up by calling some function.
The pattern is [here](https://github.com/codeceptjs/CodeceptJS/blob/4fea8c91984396feb6fba37b057bc295877bb8eb/lib/helper/extras/React.js#L7).

Then after you inject resq in a similar way, you can execute scripts in the browser, and use the selector library. I was using this method to assert on certain props in my tests.

**Comment by Xotabu4** [comment]
Would be nice to have this fixed.
