### ISSUE TITLE
TypeError: page.setUserAgent is not a function

### ISSUE THREAD

**Issue by cydalby** [codeceptjs/CodeceptJS#2899]
Trying to run Codecept Tests with Playwright but get a warn log at the start of every test.

`TypeError: page.setUserAgent is not a function`

at `codeceptjs-npm-3.0.7-bcb1d4968c-220cced1f6.zip/node_modules/codeceptjs/lib/helper/Playwright.js:615:26`

### Details

* CodeceptJS version: 3.0.7
* NodeJS Version: 14.13.1
* Operating System: Mac Mojave
* Playwright 1.10.0

**Comment by Xotabu4** [comment]
Same here, Seems like dependency Injection does not work:

```
Scenario('Some test', async ({ I, App }) => {
  App.common.commonChat.chat()
});

Cannot read property 'commonChat' of undefined
```

**Comment by elaichenkov** [comment]
Actually, there is no `setUserAgent` method in Playwright. You have to create a new context with the `userAgent` property to accomplish it (e.g. `const context = await browser.newContext({userAgent: 'foo'});`). 
Read more about the [issue](https://github.com/microsoft/playwright/issues/697)
Perhaps, it was added by copy and paste mistake, because Puppeteer has this method.

**Comment by cydalby** [comment]
Yeah thats what I mean, theres an issue in the codecept code itself as its calling page.setUserAgent in the Playwright file
