### ISSUE TITLE
Given, When, Then allows for duplicate step definitions.

### ISSUE THREAD

**Issue by raywiis** [codeceptjs/CodeceptJS#3184]
#### What are you trying to achieve?

Have the tests fail when given duplicate gherkin step definitions.

#### What do you get instead?

Tests pick up the last definition in the chain. Which leads to confusion and frustration on why the tests don't work.

### Details

* CodeceptJS version: 3.2.2
* NodeJS Version: 16.13.1
* Operating System: Ubuntu 21.10

**Comment by DavertMik** [comment]
Sure, they are by design.

You can have one definition that overrides another one:

* `Given(`I do something`)
* `When(/.*/)`

When you execute the step `I do something` both definitions may apply. So there is no guarantee that definitions do not intersect. Probably we could check for equality of definitions. This could help is this cases.

Please send Pull Request for this!

**Comment by raywiis** [comment]
Awesome. Raised a PR for this, would like to hear some feedback on it.
