### ISSUE TITLE
[ question ] Retry's on feature level

### ISSUE THREAD

**Issue by joelgrimberg** [codeceptjs/CodeceptJS#346]
Release 0.4.13 puts the retry on Feature level.
somehow I expected a retry on Config-level and not on the feature level (in my checklist).
can you explain why you choose to put it on Feature level?

**Comment by DavertMik** [comment]
Well, because it was the simplest way to implement them, it works just the same way as in Mocha. 
Probably in next version I will add option for a global config. 

I don't know for specific situation but to me retries should be set explicitly for the suites. In case the scenario is stable by execution but it fails by assertion you will have it executed few more times with the same result and that will make text execution time worse.

However, yes, I agree, setting retries in config should be an option as well.

**Comment by joelgrimberg** [comment]
@DavertMik thanx for the reply! I now see and understand. Thanx for sharing.
