### ISSUE TITLE
Regex doesn't works

### ISSUE THREAD

**Issue by BrunoExterckotter** [codeceptjs/CodeceptJS#750]
#### What are you trying to achieve?
I'm using regex to filter and don't run scripts whith @tag negated in regex

#### What do you get instead?
(?!.*@tagxyz) was unexpected in the moment.

> Provide test source code if related
Feature('@ABC @tagxyz');

Run using: codeceptjs run --grep "(?=.*@ABC)^(?!.*@tagxyz)"

Reference: http://codecept.io/advanced/

### Details

* CodeceptJS version:  "^1.0.0",

* NodeJS Version: "v6.11.2"
* Operating System: Windows 10 Pro x64
*WebDriverIO: "^4.8.0"

**Comment by APshenkin** [comment]
@BrunoExterckotter Could you please provide error message from console?
I think that maybe you should escape several symbols in your script like this:
` codeceptjs run --grep "\(\?\=\.\*@ABC\)\^\(\?\!\.\*@tagxyz)"`

**Comment by BrunoExterckotter** [comment]
![image](https://user-images.githubusercontent.com/11826014/31766788-74dcd9e4-b4a7-11e7-9e3b-81c95cb577d3.png)

The first command was accepted, but de second command was not. Apparently. Am I doing something wrong?

**Comment by BrunoExterckotter** [comment]
![image](https://user-images.githubusercontent.com/11826014/31767112-a611d770-b4a8-11e7-80ce-c05083f09a44.png)


The first command was accepted, but de second command was not. Apparently. Am I doing something wrong?

**Comment by reubenmiller** [comment]
@BrunoExterckotter Are you still have problems with the grep option?

I think this is a limitation of **mocha** as the --grep parameter is passed directly to mocha. Though you can use the `--invert --grep '@tagxyz'` which will match everything does not have the @tagxyz.

Otherwise I would recommend splitting up your tests into different folders and then define different codeceptjs config files for each. If you use the [Dynamic Configuration](https://codecept.io/configuration/) then you can `require` common configuration and only change the grep field.

**Comment by DawidTabak** [comment]
@reubenmiller I'm not sure if I should open a new issue for this, but I'm having similiar problem with grep option.
Although I don't use the inverse regex. 

I've tried to debug the issue. I noticed that options.grep is passed to mocha, however it is overwritten with the first test file. It is overwritten after ` return Mocha.prototype.loadFiles.call(mocha, fn);` is called inside mochaFactory.js 
https://github.com/Codeception/CodeceptJS/blob/72b46931dbcdc89b9a309b3748ad8db29fb7e8bf/lib/mochaFactory.js#L48

so for example, when I call `npm run codeceptjs run --grep @stable` the test first test from 'tests' glob is executed.

codeceptjs 1.3.2
node: 8.11.3
windows 10 64x
