### ISSUE TITLE
`amOnPage` assertion does not work with "/", as listed in the docs, but works with an empty string ("")

### ISSUE THREAD

**Issue by lilybarrett** [codeceptjs/CodeceptJS#855]
#### What are you trying to achieve? What do you get instead?

After setting a base URL in `codecept.json`, and when attempting to assert `amOnPage("/")` in my test, the test fails because the page cannot be found. However, `amOnPage("")` works properly.

The docs & examples, which could be out of date, use `amOnPage("/")`.

### Details

* CodeceptJS version: 1.1.1
* NodeJS Version: v8.9.4
* Operating System: macOS Sierra
* WebDriverIO: 4.9.11

**Comment by jploskonka** [comment]
Hmm, could this maybe be related to url with trailing `/` in config?
For example if your config specifies `http://localhost` as base URL then `I.amOnPage("/")` should work, but if your config sets `http://localhost/` as base URL then browser goes crazy when see two slashes?

**Comment by lilybarrett** [comment]
Thanks for the quick follow-up. Curiously enough, the base URL I specified did _not_ have a trailing slash.

I haven't attempted to replicate this with the other helpers, but perhaps this could be a WebDriverIO issue?

**Comment by reubenmiller** [comment]
@lilybarrett Do you happen to have a link to a website that is showing this behaviour? Or is this no longer an issue for you?

**Comment by thiagodp** [comment]
Hi, the same is happening here, using WebDriverIO.

@reubenmiller The problem appears to be in `amOnPage`, which ignores the config's `url` when the page starts with `/`.

For instance:
  - `url` is `http://127.0.0.1/myapp`
  - `amOnPage( '' )` (empty string) make it goes to `http://127.0.0.1/myapp`
  - `amOnPage( '/' )` make it goes to `http://127.0.0.1/` (**root url**) instead of `http://127.0.0.1/myapp`
  - `amOnPage( '/foo' )` make it goes to `http://127.0.0.1/foo` (**root url** + `/foo`) instead of `http://127.0.0.1/myapp/foo`
  - `amOnPage( '/foo/bar' )` make it goes to `http://127.0.0.1/` (**root url** + `foo/bar`) instead of `http://127.0.0.1/myapp/foo/bar`
  - and so on
